default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# DEVELOPMENT
# Connects to the PostgreSQL service defined in your docker-compose.yml file.
# It reads connection details from environment variables set by Docker Compose.
development:
  <<: *default
  database: food_app_development
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

# TEST
# This will use environment variables for the host, user, and password if they
# are present (as they are in Docker), but will fall back to localhost and
# common defaults when run natively.
test:
  <<: *default
  database: food_app_test
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

# PRODUCTION
# Configured to read from a single DATABASE_URL environment variable,
# which is a common convention for hosting providers like Heroku.
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>