default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_app_development

test:
  <<: *default
  database: food_app_test

production:
  <<: *default
  database: food_app_production
  username: food_app
  password: <%= ENV['FOOD_APP_DATABASE_PASSWORD'] %>